language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm

before_script:
  - composer install --prefer-dist --dev --no-interaction
  - composer require phpunit/phpunit=4.4.*

script:
  - mkdir -p build/logs
  - vendor/bin/phpunit -v
