language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6

before_script:
  - echo "extension = recode.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - composer install --prefer-dist --dev --no-interaction

script:
  - mkdir -p build/logs
  - vendor/bin/phpunit
